### ISSUE TITLE
Not work for LAT/LON sets (2D)

### ISSUE THREAD

**Issue by jamm1985** [lstagner/ConcaveHull.jl#3]
Here is example:

```julia
typeof(B) #Array{Array{Float64,1},1}
length(B) #223918
@time hull = concave_hull(B) 
# NOT END AFTER 30 MIN!
# AND CPU 100% ALL TIME
```

```
> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

[latlon_set.txt.zip](https://github.com/lstagner/ConcaveHull.jl/files/1633966/latlon_set.txt.zip)

**Comment by lstagner** [comment]
The issue is that you have some points that share x/y values. (I can't quite remember why this causes problems but it does) When this happens the algorithm keeps on trying to increase the number of nearest neighbors it considers. It starts at 1 and goes to the number of points which is a lot in your case which is why it didn't complete in the 30 min. To fix this you can just add a bit of random noise so that there are unique x/y values. If you do this it only takes about 20 seconds.

```
julia> using Plots, ConcaveHull
julia> a = readdlm("latlon_set.txt")
julia> x = [[a[i,1],a[i,2]] for i=1:223918]
julia> @time hull = concave_hull(x)
 20.674254 seconds (8.20 M allocations: 52.342 GiB, 45.25% gc time)
ConcaveHull.Hull{SVector{2,Float64}}
  Number of vertices: 321
  Number of neighbors used: 61
julia> Plots.scatter(a[:,1],a[:,2],ms=1)
julia> Plots.plot!(hull)
```
![figure_1-2](https://user-images.githubusercontent.com/4305891/35018588-32ee6cde-fad7-11e7-86ab-aa8e64e14ba0.png)

**Comment by jamm1985** [comment]
@lstagner thank you very much!
